from enum import Enum

class TipoMovimiento(str, Enum):
    ENTRADA = "ENTRADA"
    SALIDA = "SALIDA"
    AJUSTE = "AJUSTE"

class OrigenMovimiento(str, Enum):
    COMPRA = "COMPRA"
    COMPRA_CANCELADA = "COMPRA_CANCELADA"
    VENTA = "VENTA"
    VENTA_CANCELADA = "VENTA_CANCELADA"
    DEVOLUCION_CLIENTE = "DEVOLUCION_CLIENTE"
    DEVOLUCION_PROVEEDOR = "DEVOLUCION_PROVEEDOR"
    AJUSTE_MANUAL = "AJUSTE_MANUAL"
    AJUSTE_INVENTARIO = "AJUSTE_INVENTARIO"
    INVENTARIO_INICIAL = "INVENTARIO_INICIAL"
    CORRECCION = "CORRECCION"
    TRANSFERENCIA_ENTRADA = "TRANSFERENCIA_ENTRADA"
    TRANSFERENCIA_SALIDA = "TRANSFERENCIA_SALIDA"
    MERMA_DANO = "MERMA_DANO"
    MERMA_ROBO = "MERMA_ROBO"
    MERMA_PERDIDA = "MERMA_PERDIDA"
    IMPORTACION = "IMPORTACION"
    RESERVA = "RESERVA"
    LIBERACION_RESERVA = "LIBERACION_RESERVA"
    DONACION = "DONACION"
    MUESTRA = "MUESTRA"
    OTRO = "OTRO"
